# Pandas tutorial

2 this notebook explains.....

In [192]:
# pip install pandas
# pip install numpy

In [193]:
import pandas as pd
import numpy as np

In [194]:
# A Series is a one-dimensional labeled array,
#  while a DataFrame is a two-dimensional labeled table with rows and columns.

In [195]:
pd.Series([10, 20, 30])      #gives one labeled list of values.

0    10
1    20
2    30
dtype: int64

In [196]:
pd.DataFrame({"A": [10, 20], "B": [30, 40]})      # gives a table with two columns.

    A   B
0  10  30
1  20  40

In [197]:
# object creation
s=pd.Series([1,3,5,7,8,9])
s

0    1
1    3
2    5
3    7
4    8
5    9
dtype: int64

In [198]:
# object creation
s=pd.Series([1,3,np.nan,5,7,8,9])
s

0    1.0
1    3.0
2    NaN
3    5.0
4    7.0
5    8.0
6    9.0
dtype: float64

In [199]:
dates=pd.date_range("20130101",periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [200]:
# pandas Series has no column labels, as it is just a single column of a DataFrame.
#  A Series does have row labels.
ages = pd.Series([22, 35, 58], name="Age")

ages

0    22
1    35
2    58
Name: Age, dtype: int64

In [201]:
import seaborn as sns

# This bypasses your local folder error completely
titanic = sns.load_dataset("titanic")

In [202]:
titanic

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [203]:
titanic.head(8)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [204]:
titanic.dtypes

survived          int64
pclass            int64
sex                 str
age             float64
sibsp             int64
parch             int64
fare            float64
embarked            str
class          category
who                 str
adult_male         bool
deck           category
embark_town         str
alive               str
alone              bool
dtype: object

In [205]:
titanic.info()  # to see all the columns and their data types, as well as non-null counts.

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    category
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), str(5)
memory usage: 80.7 KB

In [206]:
titanic.to_excel("titanic.xlsx", sheet_name="passengers", index=False)
# index=False: This prevents pandas from writing the row numbers (0, 1, 2, etc.) as the very first column in your Excel sheet.
#  It keeps your Excel file clean, starting directly with your actual columns like Survived, Pclass, and Sex.

In [207]:
# pip install openpyxl  
# this library is required to write Excel files with pandas. 
# It provides the necessary functionality for pandas to create and manipulate Excel files.

In [208]:
import pandas as pd
titanic = pd.read_excel("titanic.xlsx", sheet_name="passengers")

In [209]:
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [210]:
# Use () for methods/functions.
# Use no brackets for attributes.
# Use [] for selecting data, like df["name"]

In [211]:
titanic.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    str
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    str
 8   class        891 non-null    str
 9   who          891 non-null    str
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    str
 12  embark_town  889 non-null    str
 13  alive        891 non-null    str
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), str(7)
memory usage: 92.4 KB

In [212]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [213]:
age = titanic["age"] # this gives us the "age" column as a Series.
age.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: age, dtype: float64

In [214]:
age_sex = titanic[["age", "sex"]] # this gives us a DataFrame with the "age" and "sex
age_sex.head()

    age     sex
0  22.0    male
1  38.0  female
2  26.0  female
3  35.0  female
4  35.0    male

In [215]:
above_35 = titanic[titanic["age"] > 35]     # passengers older than 35 years
above_35.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
6,0,1,male,54.0,0,0,51.8625,S,First,man,True,E,Southampton,no,True
11,1,1,female,58.0,0,0,26.5500,S,First,woman,False,C,Southampton,yes,True
13,0,3,male,39.0,1,5,31.2750,S,Third,man,True,NaN,Southampton,no,False
15,1,2,female,55.0,0,0,16.0000,S,Second,woman,False,NaN,Southampton,yes,True

In [216]:
above_35.shape

(217, 15)

In [217]:
above_35.describe()

         survived      pclass         age       sibsp       parch        fare
count  217.000000  217.000000  217.000000  217.000000  217.000000  217.000000
mean     0.382488    1.811060   46.979263    0.345622    0.465438   43.966821
std      0.487119    0.858653    9.188272    0.522983    1.075809   56.083306
min      0.000000    1.000000   36.000000    0.000000    0.000000    0.000000
25%      0.000000    1.000000   40.000000    0.000000    0.000000   12.525000
50%      0.000000    2.000000   45.000000    0.000000    0.000000   26.387500
75%      1.000000    3.000000   52.000000    1.000000    0.000000   55.900000
max      1.000000    3.000000   80.000000    2.000000    6.000000  512.329200

In [218]:
titanic.sex.value_counts()

sex
male      577
female    314
Name: count, dtype: int64

In [219]:
above_35.sex.value_counts()

sex
male      144
female     73
Name: count, dtype: int64

In [220]:
above_35['sex'].value_counts()  
# above_35['sex'].value_counts() and above_35.sex.value_counts() are equivalent and will give the same result.

sex
male      144
female     73
Name: count, dtype: int64

In [221]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [222]:
class_23 = titanic[titanic["pclass"].isin([2, 3])]       # passengers in class 2 or 3
class_23

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [223]:
class_23.shape

(675, 15)

In [224]:
class_2_and_3 = titanic[(titanic["pclass"] == 2) | (titanic["pclass"] == 3)]
class_2_and_3.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False

In [225]:
class_2_and_3.shape  # class_2_and_3.shape and class_23.shape will give the same result, 
# as they are just different ways to filter the same data.

(675, 15)

In [226]:
class_23 = titanic[(titanic["pclass"] == 2) | (titanic["pclass"] == 3)]
class_23

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
7,0,3,male,2.0,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
884,0,3,male,25.0,0,0,7.0500,S,Third,man,True,NaN,Southampton,no,True
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [227]:
age_no_na = titanic[titanic["age"].notna()] 
age_no_na
# this gives us a DataFrame with only the rows where the "age" column is not NA (not missing).

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
885,0,3,female,39.0,0,5,29.1250,Q,Third,woman,False,NaN,Queenstown,no,False
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [228]:
age_na=titanic[titanic['age'].isnull()]
age_na

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
5,0,3,male,NaN,0,0,8.4583,Q,Third,man,True,NaN,Queenstown,no,True
17,1,2,male,NaN,0,0,13.0000,S,Second,man,True,NaN,Southampton,yes,True
19,1,3,female,NaN,0,0,7.2250,C,Third,woman,False,NaN,Cherbourg,yes,True
26,0,3,male,NaN,0,0,7.2250,C,Third,man,True,NaN,Cherbourg,no,True
28,1,3,female,NaN,0,0,7.8792,Q,Third,woman,False,NaN,Queenstown,yes,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
859,0,3,male,NaN,0,0,7.2292,C,Third,man,True,NaN,Cherbourg,no,True
863,0,3,female,NaN,8,2,69.5500,S,Third,woman,False,NaN,Southampton,no,False
868,0,3,male,NaN,0,0,9.5000,S,Third,man,True,NaN,Southampton,no,True
878,0,3,male,NaN,0,0,7.8958,S,Third,man,True,NaN,Southampton,no,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False

In [229]:
# iloc uses integer-based indexing, so it selects rows 9 to 24 and columns 2 to 4 (since the end index is exclusive).
titanic.iloc[9:25, 2:5]

       sex   age  sibsp
9   female  14.0      1
10  female   4.0      1
11  female  58.0      0
12    male  20.0      0
13    male  39.0      1
14  female  14.0      0
15  female  55.0      0
16    male   2.0      4
17    male   NaN      0
18  female  31.0      1
19  female   NaN      0
20    male  35.0      0
21    male  34.0      0
22  female  15.0      0
23    male  28.0      0
24  female   8.0      3

# Create Plots in Pandas

In [230]:
import matplotlib.pyplot as plt

In [231]:
titanic = pd.read_csv("data/titanic.csv")
titanic.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [232]:
titanic["age"].mean()

np.float64(29.69911764705882)

In [233]:
titanic[["age", "fare"]].median()

age     28.0000
fare    14.4542
dtype: float64

In [234]:
titanic[["age", "fare"]].describe()

              age        fare
count  714.000000  891.000000
mean    29.699118   32.204208
std     14.526497   49.693429
min      0.420000    0.000000
25%     20.125000    7.910400
50%     28.000000   14.454200
75%     38.000000   31.000000
max     80.000000  512.329200

In [235]:
titanic.agg(
    {
        "age": ["min", "max", "median", "skew"],
        "fare": ["min", "max", "median", "mean"],
    }
)

              age        fare
min      0.420000    0.000000
max     80.000000  512.329200
median  28.000000   14.454200
skew     0.389108         NaN
mean          NaN   32.204208

In [236]:
titanic[["sex", "age"]].groupby("sex").mean()
# .groupby("sex"): Groups the rows by male and female.

              age
sex
female  27.915709
male    30.726645

In [237]:
titanic.groupby("sex").mean(numeric_only=True)

,survived,pclass,age,sibsp,parch,fare,adult_male,alone
sex,,,,,,,,
female,0.742038,2.159236,27.915709,0.694268,0.649682,44.479818,0.000000,0.401274
male,0.188908,2.389948,30.726645,0.429809,0.235702,25.523893,0.930676,0.712305

In [238]:
titanic["pclass"].value_counts().sort_index(ascending=True)
# value_counts() counts the occurrences of each unique value in the "pclass" column, and ascending=True sorts the results in ascending order.

pclass
1    216
2    184
3    491
Name: count, dtype: int64

In [239]:
titanic["pclass"].value_counts(ascending=True)  
# value_counts() counts the occurrences of each unique value in the "pclass" column, and ascending=False sorts the results in descending order.

pclass
2    184
1    216
3    491
Name: count, dtype: int64

In [240]:
titanic.groupby("pclass")["pclass"].count()

pclass
1    216
2    184
3    491
Name: pclass, dtype: int64

In [241]:
titanic.groupby("pclass")["pclass"].size()

pclass
1    216
2    184
3    491
Name: pclass, dtype: int64

In [242]:
titanic.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='str')

In [243]:
titanic.groupby("embarked")["embarked"].count()

embarked
C    168
Q     77
S    644
Name: embarked, dtype: int64

In [244]:
titanic.groupby("embarked")["embarked"].count().sort_values(ascending=True)

embarked
Q     77
C    168
S    644
Name: embarked, dtype: int64

In [245]:
168+77+644

889

In [246]:
titanic.groupby("embarked")["embarked"].size()

embarked
C    168
Q     77
S    644
Name: embarked, dtype: int64

In [247]:
titanic.sort_values(by="age",ascending=True).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
644,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
469,1,3,female,0.75,2,1,19.2583,C,Third,child,False,NaN,Cherbourg,yes,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False

In [248]:
titanic.sort_values(by="age",ascending=False).head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
630,1,1,male,80.0,0,0,30.0000,S,First,man,True,A,Southampton,yes,True
851,0,3,male,74.0,0,0,7.7750,S,Third,man,True,NaN,Southampton,no,True
493,0,1,male,71.0,0,0,49.5042,C,First,man,True,NaN,Cherbourg,no,True
96,0,1,male,71.0,0,0,34.6542,C,First,man,True,A,Cherbourg,no,True
116,0,3,male,70.5,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

# 10 minutes to pandas

In [249]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

In [250]:
dates = pd.date_range("20130101", periods=6)
dates

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [251]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list("ABCD"))
df

                   A         B         C         D
2013-01-01  0.539610  0.557096  0.958831  1.997712
2013-01-02 -0.760512  0.033867  0.730665 -0.156521
2013-01-03 -0.800015  0.319109 -0.656257  0.443457
2013-01-04 -1.651046  0.100174  0.574754  0.399121
2013-01-05  0.987681 -0.061251  0.227584 -1.649208
2013-01-06 -1.178667 -0.279261  0.783815  0.385962

In [252]:
df2 = pd.DataFrame(
    {
        "A": 1.0,
        "B": pd.Timestamp("20130102"),
        "C": pd.Series(1, index=list(range(4)), dtype="float32"),
        "D": np.array([3] * 4, dtype="int32"),
        "E": pd.Categorical(["test", "train", "test", "train"]),
        "F": "foo",
    }
)
df2

     A          B    C  D      E    F
0  1.0 2013-01-02  1.0  3   test  foo
1  1.0 2013-01-02  1.0  3  train  foo
2  1.0 2013-01-02  1.0  3   test  foo
3  1.0 2013-01-02  1.0  3  train  foo

In [253]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

- The main difference is that **df['a']** (bracket notation) is safer and works in every situation, while **df.a** (dot notation) is a shortcut that often fails depending on the column name.
- Use **df['A']** by default because it never fails. Only use **df.A** if you want to type quickly and are 100% sure your column name is a single, plain word.

In [254]:
df2['A']

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [255]:
df2.A

0    1.0
1    1.0
2    1.0
3    1.0
Name: A, dtype: float64

In [256]:
# Viewing data
df.head()

                   A         B         C         D
2013-01-01  0.539610  0.557096  0.958831  1.997712
2013-01-02 -0.760512  0.033867  0.730665 -0.156521
2013-01-03 -0.800015  0.319109 -0.656257  0.443457
2013-01-04 -1.651046  0.100174  0.574754  0.399121
2013-01-05  0.987681 -0.061251  0.227584 -1.649208

In [257]:
df.tail() # gives us the last 5 rows of the DataFrame by default.

                   A         B         C         D
2013-01-02 -0.760512  0.033867  0.730665 -0.156521
2013-01-03 -0.800015  0.319109 -0.656257  0.443457
2013-01-04 -1.651046  0.100174  0.574754  0.399121
2013-01-05  0.987681 -0.061251  0.227584 -1.649208
2013-01-06 -1.178667 -0.279261  0.783815  0.385962

In [258]:
df.index # gives us the row labels (the index) of the DataFrame.
# refers to the row labels of your DataFrame.
# While columns represent your vertical fields (attributes),
# the index represents your horizontal fields (the rows).

DatetimeIndex(['2013-01-01', '2013-01-02', '2013-01-03', '2013-01-04',
               '2013-01-05', '2013-01-06'],
              dtype='datetime64[us]', freq='D')

In [259]:
titanic.index

RangeIndex(start=0, stop=891, step=1)

In [260]:
df.columns      # for areas where you want to access the column labels as an attribute, 
# like df.columns, which gives you the list of column names.

Index(['A', 'B', 'C', 'D'], dtype='str')

In [261]:
# For a DataFrame, passing a slice : selects matching rows
df[0:3]  # selects the first three rows of the DataFrame.

                   A         B         C         D
2013-01-01  0.539610  0.557096  0.958831  1.997712
2013-01-02 -0.760512  0.033867  0.730665 -0.156521
2013-01-03 -0.800015  0.319109 -0.656257  0.443457

In [ ]:
df.to_numpy()    # converts the DataFrame into a NumPy array,
#  which is a more basic data structure for numerical computations.
# NumPy arrays have one dtype for the entire array while pandas DataFrames have one dtype per column

array([[-2.07616157,  0.55777388,  1.12183703,  1.39226332],
       [ 0.10456462,  0.17993478,  0.16994018, -0.58726192],
       [-0.39285765,  1.24638313,  0.15029293, -0.9369432 ],
       [-0.62067942,  0.52038922,  2.43832242, -1.04581062],
       [ 0.12578339, -0.96759194, -1.67533221, -0.41407917],
       [-1.41584483, -0.32344964, -0.10630607, -0.13259946]])

In [80]:
df2.dtypes

A           float64
B    datetime64[us]
C           float32
D             int32
E          category
F               str
dtype: object

In [81]:
df2.to_numpy()

array([[1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'test', 'foo'],
       [1.0, Timestamp('2013-01-02 00:00:00'), 1.0, 3, 'train', 'foo']],
      dtype=object)

In [82]:
df.describe()

              A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean  -0.712533  0.202240  0.349792 -0.287405
std    0.875806  0.769833  1.366698  0.888627
min   -2.076162 -0.967592 -1.675332 -1.045811
25%   -1.217053 -0.197604 -0.042156 -0.849523
50%   -0.506769  0.350162  0.160117 -0.500671
75%   -0.019791  0.548428  0.883863 -0.202969
max    0.125783  1.246383  2.438322  1.392263

In [83]:
df.describe().transpose()

   count      mean       std       min       25%       50%       75%       max
A    6.0 -0.712533  0.875806 -2.076162 -1.217053 -0.506769 -0.019791  0.125783
B    6.0  0.202240  0.769833 -0.967592 -0.197604  0.350162  0.548428  1.246383
C    6.0  0.349792  1.366698 -1.675332 -0.042156  0.160117  0.883863  2.438322
D    6.0 -0.287405  0.888627 -1.045811 -0.849523 -0.500671 -0.202969  1.392263

In [84]:
df.T

   2013-01-01  2013-01-02  2013-01-03  2013-01-04  2013-01-05  2013-01-06
A   -2.076162    0.104565   -0.392858   -0.620679    0.125783   -1.415845
B    0.557774    0.179935    1.246383    0.520389   -0.967592   -0.323450
C    1.121837    0.169940    0.150293    2.438322   -1.675332   -0.106306
D    1.392263   -0.587262   -0.936943   -1.045811   -0.414079   -0.132599

In [ ]:
df.sort_index(axis=1, ascending=False)
# That line of code reorders your DataFrame's columns alphabetically from Z to A.

                   D         C         B         A
2013-01-01  1.392263  1.121837  0.557774 -2.076162
2013-01-02 -0.587262  0.169940  0.179935  0.104565
2013-01-03 -0.936943  0.150293  1.246383 -0.392858
2013-01-04 -1.045811  2.438322  0.520389 -0.620679
2013-01-05 -0.414079 -1.675332 -0.967592  0.125783
2013-01-06 -0.132599 -0.106306 -0.323450 -1.415845

In [ ]:
df.sort_index(axis=0, ascending=False)  
# The axis along which to sort. The value 0 identifies the rows, and 1 identifies the columns. default 0

                   A         B         C         D
2013-01-06 -1.415845 -0.323450 -0.106306 -0.132599
2013-01-05  0.125783 -0.967592 -1.675332 -0.414079
2013-01-04 -0.620679  0.520389  2.438322 -1.045811
2013-01-03 -0.392858  1.246383  0.150293 -0.936943
2013-01-02  0.104565  0.179935  0.169940 -0.587262
2013-01-01 -2.076162  0.557774  1.121837  1.392263

In [87]:
df.sort_values(by="B")
# sort by values in column B

                   A         B         C         D
2013-01-05  0.125783 -0.967592 -1.675332 -0.414079
2013-01-06 -1.415845 -0.323450 -0.106306 -0.132599
2013-01-02  0.104565  0.179935  0.169940 -0.587262
2013-01-04 -0.620679  0.520389  2.438322 -1.045811
2013-01-01 -2.076162  0.557774  1.121837  1.392263
2013-01-03 -0.392858  1.246383  0.150293 -0.936943

In [88]:
df[["B", "A"]]

                   B         A
2013-01-01  0.557774 -2.076162
2013-01-02  0.179935  0.104565
2013-01-03  1.246383 -0.392858
2013-01-04  0.520389 -0.620679
2013-01-05 -0.967592  0.125783
2013-01-06 -0.323450 -1.415845

In [263]:
df

                   A         B         C         D
2013-01-01  0.539610  0.557096  0.958831  1.997712
2013-01-02 -0.760512  0.033867  0.730665 -0.156521
2013-01-03 -0.800015  0.319109 -0.656257  0.443457
2013-01-04 -1.651046  0.100174  0.574754  0.399121
2013-01-05  0.987681 -0.061251  0.227584 -1.649208
2013-01-06 -1.178667 -0.279261  0.783815  0.385962

## Selection by label
- See more in Selection by Label using DataFrame.loc() or DataFrame.at().
- Selecting a row matching a label:

In [262]:
df.loc[dates[0]]

A    0.539610
B    0.557096
C    0.958831
D    1.997712
Name: 2013-01-01 00:00:00, dtype: float64

In [264]:
# Selecting all rows (:) with a select column labels:
df.loc[:, ["A", "B"]]

                   A         B
2013-01-01  0.539610  0.557096
2013-01-02 -0.760512  0.033867
2013-01-03 -0.800015  0.319109
2013-01-04 -1.651046  0.100174
2013-01-05  0.987681 -0.061251
2013-01-06 -1.178667 -0.279261

In [ ]:
# For label slicing, both endpoints are included:
df.loc["20130102":"20130104", ["A", "B"]] # df.loc[row_labels, column_labels]
# row=20130102 to 20130104, columns A to B

                   A         B
2013-01-02 -0.760512  0.033867
2013-01-03 -0.800015  0.319109
2013-01-04 -1.651046  0.100174

In [269]:
# Selecting a single row and column label returns a scalar:
df.loc[dates[0], "A"]

np.float64(0.5396095810267972)

In [ ]:
# For getting fast access to a scalar (equivalent to the prior method):
df.at[dates[0], "A"]  # df.at is optimized for getting and setting a single value in the DataFrame,
#  so it's faster than df.loc for this specific use case.

np.float64(0.5396095810267972)

# Selection by position
- Selection by Position using DataFrame.iloc() or DataFrame.iat().
- The position of the passed integers:

In [ ]:
df.iloc[3] # selects the fourth row of the DataFrame (since indexing starts at 0).

A   -1.651046
B    0.100174
C    0.574754
D    0.399121
Name: 2013-01-04 00:00:00, dtype: float64

The fundamental difference between **.loc** and **.iloc** comes down to how they look up data:\
 **.loc** is label-based (it looks for names), while **.iloc** is integer-based (it looks for numeric index positions).

In [272]:
# Integer slices acts similar to NumPy/Python:
df.iloc[3:5, 0:2]

                   A         B
2013-01-04 -1.651046  0.100174
2013-01-05  0.987681 -0.061251

In [273]:
# Lists of integer position locations:
df.iloc[[1, 2, 4], [0, 2]]

                   A         C
2013-01-02 -0.760512  0.730665
2013-01-03 -0.800015 -0.656257
2013-01-05  0.987681  0.227584

In [ ]:
# For slicing rows explicitly:
df.iloc[1:3, :] 
# selects rows 1 and 2 (since the end index is exclusive) and all columns (:) of the DataFrame.

                   A         B         C         D
2013-01-02 -0.760512  0.033867  0.730665 -0.156521
2013-01-03 -0.800015  0.319109 -0.656257  0.443457

In [ ]:
# For slicing columns explicitly:
df.iloc[:, 1:3]
# selects all rows (:) and columns 1 and 2 (since the end index is exclusive) of the DataFrame.

                   B         C
2013-01-01  0.557096  0.958831
2013-01-02  0.033867  0.730665
2013-01-03  0.319109 -0.656257
2013-01-04  0.100174  0.574754
2013-01-05 -0.061251  0.227584
2013-01-06 -0.279261  0.783815

In [276]:
# For getting a value explicitly:
df.iloc[1, 1]

np.float64(0.0338673508453993)

In [277]:
# For getting fast access to a scalar (equivalent to the prior method):
df.iat[1, 1]

np.float64(0.0338673508453993)

The fundamental difference between **.iat** and **.iloc** is speed and scope: **.iat** is a specialized tool designed to extract or change a single, individual cell as fast as possible, while **.iloc** is a general tool that can select multiple rows, columns, or entire slices of data.Both use integer-based positions (0, 1, 2...) to look up data, but they serve different optimization needs.

# Boolean indexing

In [278]:
# Select rows where df.A is greater than 0.
df[df["A"] > 0]

                   A         B         C         D
2013-01-01  0.539610  0.557096  0.958831  1.997712
2013-01-05  0.987681 -0.061251  0.227584 -1.649208

# Operations
## Stats

In [279]:
# Calculate the mean value for each column:
df.mean()

A   -0.477158
B    0.111622
C    0.436565
D    0.236754
dtype: float64

In [ ]:
df.mean(axis=0)  # Calculate the mean value for each column

A   -0.477158
B    0.111622
C    0.436565
D    0.236754
dtype: float64

In [280]:
# Calculate the mean value for each row:
df.mean(axis=1)

2013-01-01    1.013312
2013-01-02   -0.038125
2013-01-03   -0.173427
2013-01-04   -0.144249
2013-01-05   -0.123798
2013-01-06   -0.072038
Freq: D, dtype: float64

In [282]:
df.agg(lambda x: np.mean(x) * 5.6)

A   -2.672087
B    0.625086
C    2.444766
D    1.325821
dtype: float64

In [283]:
df.transform(lambda x: x * 101.2)

                     A          B          C           D
2013-01-01   54.608490  56.378093  97.033684  202.168418
2013-01-02  -76.963795   3.427376  73.943344  -15.839925
2013-01-03  -80.961547  32.293845 -66.413175   44.877806
2013-01-04 -167.085833  10.137609  58.165058   40.391022
2013-01-05   99.953282  -6.198566  23.031499 -166.899840
2013-01-06 -119.281147 -28.261213  79.322033   39.059346

# Value Counts

In [284]:
s = pd.Series(np.random.randint(0, 7, size=10))
s

0    3
1    5
2    3
3    2
4    3
5    5
6    6
7    1
8    5
9    3
dtype: int32

In [285]:
s.value_counts()

3    4
5    3
2    1
6    1
1    1
Name: count, dtype: int64

# String Methods

In [286]:
s = pd.Series(["A", "B", "C", "Aaba", "Baca", np.nan, "CABA", "dog", "cat"])

s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: str

# Merge
## Concat
- pandas provides various facilities for easily combining together Series and DataFrame objects with various kinds of set logic for the indexes and relational algebra functionality in the case of join / merge-type operations.

In [287]:
# Concatenating pandas objects together row-wise with concat():
df = pd.DataFrame(np.random.randn(10, 4))
df

          0         1         2         3
0 -1.754775  0.034229 -0.354539 -0.635722
1 -1.568579  0.084271 -0.801835 -1.408870
2  0.594519 -1.862277 -2.190220  0.585230
3 -0.035260 -2.365979 -0.700772 -0.654702
4 -0.923472  0.315170  0.477387  0.955054
5  0.469150  0.521841  0.266555  0.374025
6  0.806038  0.501375 -0.358037 -0.254554
7 -1.811608 -1.514384  1.232208  0.425194
8 -0.852664  0.397473  0.080406  1.249692
9  0.041212 -0.791288 -1.823461 -0.940483

In [288]:
# break it into pieces
pieces = [df[:3], df[3:7], df[7:]]

In [289]:
pieces

[          0         1         2         3
 0 -1.754775  0.034229 -0.354539 -0.635722
 1 -1.568579  0.084271 -0.801835 -1.408870
 2  0.594519 -1.862277 -2.190220  0.585230,
           0         1         2         3
 3 -0.035260 -2.365979 -0.700772 -0.654702
 4 -0.923472  0.315170  0.477387  0.955054
 5  0.469150  0.521841  0.266555  0.374025
 6  0.806038  0.501375 -0.358037 -0.254554,
           0         1         2         3
 7 -1.811608 -1.514384  1.232208  0.425194
 8 -0.852664  0.397473  0.080406  1.249692
 9  0.041212 -0.791288 -1.823461 -0.940483]

In [290]:
pd.concat(pieces)

          0         1         2         3
0 -1.754775  0.034229 -0.354539 -0.635722
1 -1.568579  0.084271 -0.801835 -1.408870
2  0.594519 -1.862277 -2.190220  0.585230
3 -0.035260 -2.365979 -0.700772 -0.654702
4 -0.923472  0.315170  0.477387  0.955054
5  0.469150  0.521841  0.266555  0.374025
6  0.806038  0.501375 -0.358037 -0.254554
7 -1.811608 -1.514384  1.232208  0.425194
8 -0.852664  0.397473  0.080406  1.249692
9  0.041212 -0.791288 -1.823461 -0.940483

# Join

In [303]:
left = pd.DataFrame({"key": ["foo", "foo"], "lval": [1, 2]})
left

   key  lval
0  foo     1
1  foo     2

In [304]:
right = pd.DataFrame({"key": ["foo", "foo"], "rval": [4, 5]})
right

   key  rval
0  foo     4
1  foo     5

In [305]:
pd.merge(left, right, on="key")

   key  lval  rval
0  foo     1     4
1  foo     1     5
2  foo     2     4
3  foo     2     5

# Grouping
By “group by” we are referring to a process involving one or more of the following steps:

- Splitting the data into groups based on some criteria
- Applying a function to each group independently
- Combining the results into a data structure